### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by eunrui** [flymin/Hackintosh-Thinkpad-X1-Extreme#1]
作者您好~
我的触摸板只有登录界面才能动诶 :(
和您的配置一样
进入系统就不起作用了
只能换成以前版本的VoodooPS2 
但是这样手势就不支持几个了!!
您知道什么解决的办法嘛

**Comment by flymin** [comment]
我用的是acidanthera的[VoodooPS2](https://github.com/acidanthera/VoodooPS2/releases)，从2.1.0开始需要配合[VoodooInput](https://github.com/acidanthera/VoodooInput/releases)使用了。确实出现过偶尔睡眠唤醒触控板失灵的情况，不过我没在意。

**Comment by eunrui** [comment]
> 我用的是acidanthera的[VoodooPS2](https://github.com/acidanthera/VoodooPS2/releases)，从2.1.0开始需要配合[VoodooInput](https://github.com/acidanthera/VoodooInput/releases)使用了。确实出现过偶尔睡眠唤醒触控板失灵的情况，不过我没在意。

谢谢您的回复，还是不好使诶。

**Comment by eunrui** [comment]
好使了.. 原来是开启了`有线鼠标或无限触控板时忽略内建触控板`
