### ISSUE TITLE
关于休眠掉电问题，OC-little补丁如何使用？

### ISSUE THREAD

**Issue by wdde** [flymin/Hackintosh-Thinkpad-X1-Extreme#4]
目前我的系统休眠掉电1小时1%～2%，我看到你提到了休眠掉电可以通过OC-little/10-PTSWAK综合扩展补丁来解决，能否详细说一下进行补丁，我当前使用zysuper的OC引导，8850H机型

**Comment by flymin** [comment]
那个repo里教程挺详细的，具体好像不用改太多。

你是用的那个版本的系统？我是在10.15.4的时候解决的这个问题，10.15.6的时候重置nvram有效。但是升级到10.15.7之后可能一晚上掉5%，重置nvram也没用，我就没管了。

**Comment by wdde** [comment]
感谢回复！我是10.14.6, 仅仅涉及dsdt的补丁是吗？

**Comment by wdde** [comment]
在耗电理想的情况下，你的系统休眠的耗电怎么样？无线网络是关闭还是一直开启状态？

**Comment by wdde** [comment]
![image](https://user-images.githubusercontent.com/10916526/95961787-1c425a00-0e38-11eb-842c-81161e0d698e.png)
目前zysuper的OC,已经没有dsdt了，那么这个补丁该怎么打，OC-LITTLE的wiki貌似没提到

**Comment by flymin** [comment]
无线开启，那个repo里的补丁都是OC用的dsdt热补丁（不同型号的电脑需要修改一些值，具体这台电脑对原版来说用不用改我也忘了...），理论上你直接用我的也没事，放进去就行，config加载一下。

**Comment by flymin** [comment]
@wdde 不好意思我记错了...[这个页面](https://ocbook.tlhub.cn/10-PTSWAK%E7%BB%BC%E5%90%88%E6%89%A9%E5%B1%95%E8%A1%A5%E4%B8%81/)的更名有说明，需要在config里面完成更名，具体的参考你的dsdt是什么。比如有` Method (_PTS, 1, NotSerialized)`就使用`_PTS` to `ZPTS(1,N)`这样。

**Comment by wdde** [comment]
嗯，看上去要仔细研究一下才能实施，我先看看，谢谢你的回复！
