### ISSUE TITLE
10.13能把独显驱动起来吗？

### ISSUE THREAD

**Issue by hyperzlib** [flymin/Hackintosh-Thinkpad-X1-Extreme#5]

**Comment by flymin** [comment]
没装过那么低的版本，现在都是屏蔽独显装的。按说有 web drive 应该能驱动。

**Comment by hyperzlib** [comment]
低版本用高版本的EFI驱动不了

**Comment by flymin** [comment]
> 低版本用高版本的EFI驱动不了

完全驱动不了不应该吧，我记得 OC 适配了低版本的 macos...要不你从这个仓库里找找之前的 clover 的 EFI 试试
