### ISSUE TITLE
关于升级Big Sur

### ISSUE THREAD

**Issue by hyperzlib** [flymin/Hackintosh-Thinkpad-X1-Extreme#6]
我把Lilu系列的插件全部升级过了，但是在安装BigSur的时候提示TextInputMenuAgent文件不存在。

**Comment by flymin** [comment]
我目前没有尝试 Big Sur，但是这个问题看起来不是驱动的事？新版的 OC 倒是更新了一项关于 Big Sur 的问题：
![image](https://user-images.githubusercontent.com/28671430/101719002-5f8a1380-3add-11eb-8f75-786cdbe994f4.png)
但我觉得和你这个报错没有关系，要不换个镜像试试？
