### ISSUE TITLE
期待更新的发布

### ISSUE THREAD

**Issue by meng004** [flymin/Hackintosh-Thinkpad-X1-Extreme#7]
因为及时更新，所以一直关注本 repo，五天前发布了7.0版本，flymin的辛勤劳动值得肯定。
为方便分享，请提供release，谢谢。
新年快乐

**Comment by flymin** [comment]
Actually, you can just download the corresponding folder.
Anyway, [here](https://github.com/flymin/Hackintosh-Thinkpad-X1-Extreme/releases/tag/v10.15.7.6.0) it is.
